### ISSUE TITLE
Request #20 publish to npm

### ISSUE THREAD

**Issue by djeeg** [aweary/react-perimeter#24]
Hi,

Related to https://github.com/aweary/react-perimeter/pull/20

I see that the PropTypes have been upgraded to [prop-types]
https://github.com/aweary/react-perimeter/blob/master/src/index.js#L48-L60

Though it looks like 0.3.1 published to NPM still has the references to React.PropTypes
https://unpkg.com/react-perimeter@0.3.1/lib/index.js

```
Perimeter.propTypes = {
  onBreach: _react2.default.PropTypes.func.isRequired,
  once: _react2.default.PropTypes.bool,
  padding: _react2.default.PropTypes.number.isRequired,
  mapListeners: _react2.default.PropTypes.func
};
Perimeter.contextTypes = {
  listener: _react2.default.PropTypes.shape({
    add: _react2.default.PropTypes.func.isRequired,
    remove: _react2.default.PropTypes.func.isRequired
  })
};
```

Cheers

**Comment by aweary** [comment]
Hey, @djeeg! Thanks for reminding me of this. I've published `0.4.0` which should include these changes.

https://unpkg.com/react-perimeter@0.4.0/lib/index.js

Thanks!
